import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.scss";

import Navbar from "./components/ui/navbar/Navbar";

const fonts = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
